baseURL = 'http://lmp.kerneltravel.net/docs/'
languageCode = 'zh'
title = 'lmp'

theme = "hugo-theme-learn"

metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
defaultContentLanguage = "zh"

[params]
  description = "LMP：Linux microscope"
  author = "LMP"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.zh]
title = "LMP：Linux microscope"
weight = 1
languageName = "简体中文"
landingPageURL = "/zh"
landingPageName = "<i class='fas fa-home'></i> 主页"

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> 使用案例介绍"
url = "showcase"
weight = 11

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> 文档撰写规范"
url = "/docstyle"
weight = 30
